---
driver:
  name: ec2
  instance_type: t2.medium
  iam_profile_name: backupFullAccess
  aws_ssh_key_id: automation-rpa
  security_group_ids: ["sg-070b85c34582098c6"]
  require_chef_omnibus: true
  subnet_id: subnet-0b3da7795643e140c
  shared_credentials_profile: nsagro
  associate_public_ip: true
  user_data: user_data_script.sh
## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15

verifier:
  name: inspec

platforms:
  - name: centos-7
    associate_public_ip: true
    block_device_mappings:
      - device_name: /dev/sdb
        ebs:
          volume_type: gp2
          virtual_name: test
          volume_size: 20
          delete_on_termination: true
    transport:
      username: centos
      ssh_key: /Users/cfelce/devops/kp/automation-rpa-virginia.pem 

suites:
  - name: default
    run_list:
      - recipe[f_sapcc::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
