---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      provision_command: true
      dns:
      - 8.8.8.8
      - 8.8.4.4
      forward:
      - 80:80
      privileged: true
  - name: centos-7
    driver:
      provision_command: true
      dns:
      - 8.8.8.8
      - 8.8.4.4
      forward:
      - 8443:8443
      privileged: true

suites:
  - name: default
    run_list:
      - recipe[f_sapcc::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
