---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  chef_license: accept-no-persist
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      provision_command: true
      dns:
      - 8.8.8.8
      - 8.8.4.4
      forward:
      - 80:80
      privileged: true
  - name: centos-7
    driver:
      provision_command: true
      dns:
      - 8.8.8.8
      - 8.8.4.4
      forward:
      - 8443:8443
      privileged: true
      run_options: --add-host "devfiori.cyt.conchaytoro.cl:172.16.65.27" --add-host "ecd.agrosuper.cl:192.168.9.70" --add-host "ecq.agrosuper.cl:192.168.9.89" --add-host "ngd.agrosuper.cl:192.168.19.61" --add-host "ngq.agrosuper.cl:192.168.19.62" --add-host "ngp.agrosuper.cl:192.168.19.60" 

suites:
  - name: default
    run_list:
      - recipe[f_sapcc::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
