---
driver:
  name: dokken

transport:
  name: dokken

provisioner:
  name: dokken
  # chef_license: accept-no-persist
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image: dokken/centos-7

suites:
  - name: default
    driver:
      ports:
      - '8443'
    run_list:
      - recipe[f_sapcc::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
